kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- namespace.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- service-account.yaml
- daemon-set.yaml
- traefik-dashboard-service.yaml
- traefik-dashboard-ingress.yaml

namespace: traefik

commonLabels:
  app: traefik