kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pihole-local-dnsmasq-claim
  namespace: pihole
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      directory: dnsmasq.d