kind: PersistentVolume
apiVersion: v1
metadata:
  name: pihole-local-dnsmasq-volume
  labels:
    directory: dnsmasq.d
  namespace: pihole
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local
  local:
    path: /tmp/dnsmasq
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - clusterfuck-4