kind: PersistentVolume
apiVersion: v1
metadata:
  name: pihole-local-etc-volume
  labels:
    directory: etc
    namespace: pihole
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local
  local:
    path: /tmp/pihole
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - clusterfuck-4